name: Python CI

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches: [ main ]

env:  
  NEO4J_USER: neo4j
  NEO4J_PASSWORD: password
  NEO4J_CONTAINER_NAME: test

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        options: >- 
          --name test
          --health-cmd "cypher-shell -u neo4j -p password 'RETURN 1;' || exit 1"
          --health-interval 2s
          --health-timeout 5s
          --health-retries 10
        ports:                    
          - 7474:7474 # used for http
          - 7687:7687 # used for bolt
        env:       
          NEO4J_AUTH: ${{ env.NEO4J_USER }}/${{ env.NEO4J_PASSWORD }} 
          NEO4J_apoc_export_file_enabled: "true"
          NEO4J_apoc_import_file_enabled: "true"
          NEO4J_apoc_import_file_use__neo4j__config: "true"
          NEO4J_PLUGINS: '["apoc", "apoc-extended"]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: test jsonToTCM
        run: python3.14 arcane2graph/jsonToTCM.py test
        
      - name: test TCMtoTSM
        run: python3.14 arcane2graph/TCMtoTSM.py test
        
      - name: test TSMtoDB
        run: |
          python3.14 arcane2graph/TSMtoNeo4j.py test bolt://localhost:7687 ${{ env.NEO4J_USER }} ${{ env.NEO4J_PASSWORD }}
